### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by just-boris** [jlongster/prettier-atom#5]
**Atom Version**: 1.12.9
**Electron Version**: 1.3.13
**System**: Ubuntu 16.04.1
**Thrown From**: [prettier-atom](https://github.com/jlongster/prettier-atom) package, v0.0.3

When I tried to install this package, it gave me the following error

```
At Cannot find module 'source-map'

Error: Cannot find module 'source-map'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (/usr/share/atom/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/bserdiuk/.atom/packages/prettier-atom/node_modules/prettier/src/printer.js:2:17)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:201:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/bserdiuk/.atom/packages/prettier-atom/node_modules/prettier/index.js:2:41)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:201:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/bserdiuk/.atom/packages/prettier-atom/lib/prettier.js:5:16)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:201:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
```

And the error is actually true, there is no source-map module in the `prettier` package dependencies.
How did it use to work?

**Comment by jlongster** [comment]
This should be fixed after updating to the latest prettier version. Please try it!

**Comment by just-boris** [comment]
Now that works.

Many thanks for your work!
